### PR TITLE
Clarifying license expectations

### LINKED ISSUE #132: Project policy is too restrictive wrt license - all doc projects are out of compliance
The current project policy requires that projects use an OSI approved license. However, documentation projects (ASVS, SCVS, etc) all use Creative Commons licenses which are not OSI approved. Technically, these projects are out of compliance with our own policy.

I will propose alternative language that continues to include OSI, but leaves the door open for other open and non-restrictive licenses, such as Creative Commons.

### PR DESCRIPTION
**Pull request by stevespringett**
This issue resolves #132 where all documentation projects are out of compliance with our own policy. The language provides an organic path to an international standard, and it leaves open the possibility of exceptions which must be approved by the project committee.

### CODE REVIEW

**Review by rewtd — COMMENTED** [review]
This change looks to be a good one. I'll bring it to the board for approval.

**Comment by kingthorin** [comment]
LGTM.

WSTG has always been licensed via Creative Commons(as far as I recall), and I actually assumed that was OSI approved (can't speak for other or past leads).

Thanks for tackling this.

**Review by rewtd — APPROVED** [review]
With four "yay" votes from the Board already, this change is approved.

**Comment by kingthorin** [comment]
Should these docs carry an update date? They currently have an “Adopted by board” date but if they’ve been subsequently updated shouldn’t that be noted too?

If they remain unchanged for the duration of the review period, every three years then it should be a no brainer for the board to rubber stamp them.

It should probably also be obvious to the community that interim changes have occurred.

Note this isn’t at all specific to this change I just happened to be looking at license details for someone 😉

**Comment by rewtd** [comment]
This is not a terrible idea, and one that could be automated from GitHub commits even... @hblankenship what are your thoughts?

**Comment by kingthorin** [comment]
Ping

**Comment by hblankenship** [comment]
I am indifferent. I think the Adopted by the Board should reflect this change and any changes that are actually adopted by the board. With minor changes (spelling, etc.), I think github handles it effectively already.

**Comment by kingthorin** [comment]
So we just need to ensure that people are updating the adopted date when tweaking these things.

**Pull request merged**
